name: Redis Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  redis-tests:
    name: Redis Integration & E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      REDIS_URL: redis://127.0.0.1:6379
      REDIS_USED_NONCE_TTL_SECS: 604800
      REDIS_PRELOAD_CAS_SCRIPT: "true"
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Wait for Redis
        run: |
          for i in {1..30}; do
            if redis-cli -h 127.0.0.1 ping | grep -q PONG; then
              echo "Redis is up"
              exit 0
            fi
            sleep 1
          done
          echo "Redis did not start" && exit 1

      - name: Run Redis E2E tests
        run: |
          set -o pipefail
          cargo test --test e2e_refresh_rotation_redis -- --nocapture 2>&1 | tee redis-test.log
          cargo test --test e2e_refresh_reuse_redis -- --nocapture 2>&1 | tee -a redis-test.log

      - name: Upload Redis logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: redis-test-log
          path: redis-test.log

      - name: Run full test suite
        run: |
          set -o pipefail
          cargo test --all --jobs 2 2>&1 | tee full-test.log

      - name: Upload full test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-test-log
          path: full-test.log
