name: Redis integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-redis:
    name: Redis integration tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      REDIS_URL: redis://127.0.0.1:6379
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Rust (install if missing)
        run: |
          if ! command -v rustc > /dev/null; then
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
            echo "source $HOME/.cargo/env" >> $GITHUB_ENV
          fi
          rustup default stable

      - name: Cache cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Show Rust version
        run: rustc --version

      - name: Run Redis integration tests (capture logs)
        run: |
          set -o pipefail
          # Run both Redis-backed e2e tests and capture logs into a single file
          cargo test --test e2e_refresh_rotation_redis -- --nocapture 2>&1 | tee redis-test.log
          cargo test --test e2e_refresh_reuse_redis -- --nocapture 2>&1 | tee -a redis-test.log

      - name: Upload Redis test logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: redis-test-log
          path: redis-test.log

      - name: Run full test suite (capture logs)
        run: |
          set -o pipefail
          cargo test --all --jobs 2 2>&1 | tee full-test.log

      - name: Upload full test logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: full-test-log
          path: full-test.log
