name: Redis Integration Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  redis-tests:
    name: Redis Integration & E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379/tcp
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      REDIS_URL: redis://127.0.0.1:${{ job.services.redis.ports[6379] }}
      REDIS_USED_NONCE_TTL_SECS: 604800
      REDIS_PRELOAD_CAS_SCRIPT: "true"
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@<pin-a-commit-sha>
        with:
          toolchain: stable

      - name: Detect rustc
        id: rustv
        run: echo "version=$(rustc -V)" >> "$GITHUB_OUTPUT"

      - name: Cache cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ steps.rustv.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Wait for Redis は削除（services の healthcheck に任せる）

      - name: Run Redis E2E tests
        run: |
          set -o pipefail
          cargo test --test e2e_refresh_rotation_redis -- --nocapture 2>&1 | tee redis-test.log
          cargo test --test e2e_refresh_reuse_redis -- --nocapture 2>&1 | tee -a redis-test.log

      - name: Upload Redis logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: redis-test-log
          path: redis-test.log

      - name: Run unit & bin tests (avoid duplicate E2E)
        run: |
          set -o pipefail
          cargo test --workspace --lib --bins 2>&1 | tee full-test.log

      - name: Upload full test logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: full-test-log
          path: full-test.log
